import {
  AlertTriangle, ArrowUpRight, Globe, Landmark, Mail, MessageSquareText,
  Shield, ShieldAlert, Smartphone, TrendingUp, Wifi,
} from "lucide-react";
import { useState } from "react";
import ActionModal from "./ActionModal";

const NEWS_ITEMS = [
  {
    id: 1,
    category: "threat-alert",
    title: "Rise in M-Pesa Reversal Scams Targeting Kenyans",
    summary: "A new wave of SMS scams impersonating Safaricom M-Pesa are circulating, requesting users to dial USSD codes that silently initiate money transfers.",
    body: `Cybersecurity analysts have observed a significant increase in M-Pesa reversal scams across Kenya in 2026.\n\n## How It Works\n\nScammers send a fake M-Pesa confirmation SMS claiming money was sent to you "by mistake." They then call, posing as the sender, begging you to reverse the transaction.\n\n## Key Details\n\n- Fake SMS messages closely mimic official Safaricom formatting\n- Victims are asked to dial USSD codes like *334# that initiate real transfers\n- Some scammers use spoofed caller IDs to appear as Safaricom numbers\n\n## How to Stay Safe\n\n1. Always verify your actual M-Pesa balance before acting\n2. Never dial USSD codes requested by strangers\n3. Use CyberSense SMS Scanner to verify suspicious messages\n4. Report scam numbers to Safaricom (0722 002 100)`,
    date: "2026-07-10",
    severity: "high",
    Icon: Smartphone,
  },
  {
    id: 2,
    category: "advisory",
    title: "Critical Vulnerability in Popular Browser Extensions",
    summary: "Several widely-used browser extensions were found to contain data-harvesting code, affecting millions of Chrome and Edge users worldwide.",
    body: `Security researchers have identified malicious code in 18 popular browser extensions with over 4 million combined downloads.\n\n## Affected Extensions\n\nThe compromised extensions include PDF converters, screenshot tools, and ad blockers that were injected with data-harvesting scripts after being sold to new developers.\n\n## What Was Collected\n\n- Browsing history and search queries\n- Login credentials entered on websites\n- Personal data from forms\n- Session cookies for popular services\n\n## Action Required\n\n1. Review your installed browser extensions immediately\n2. Remove any extensions you no longer use\n3. Only install extensions from verified developers\n4. Check extension permissions and revoke unnecessary access\n5. Change passwords for important accounts if you had suspicious extensions`,
    date: "2026-07-08",
    severity: "critical",
    Icon: Globe,
  },
  {
    id: 3,
    category: "insight",
    title: "AI-Generated Phishing Emails Now Bypass 94% of Filters",
    summary: "New research shows that AI-crafted phishing emails are significantly more effective at evading traditional security filters compared to human-written ones.",
    body: `A study published by cybersecurity firm Abnormal Security reveals that phishing emails generated by large language models bypass enterprise email security at an alarming rate.\n\n## Key Findings\n\n- AI-generated phishing bypasses 94% of traditional email filters\n- Click-through rates on AI phishing are 3x higher than manual campaigns\n- AI can personalize emails using scraped social media data in seconds\n- Grammar and spelling — traditional red flags — are now flawless\n\n## Why This Matters\n\nThe "look for spelling mistakes" advice is now outdated. AI phishing emails are:\n- Grammatically perfect\n- Contextually relevant\n- Personalized to the target\n- Generated at massive scale\n\n## New Defence Strategies\n\n1. Focus on behavioral indicators, not language quality\n2. Verify unexpected requests through independent channels\n3. Use advanced email scanning tools like CyberSense\n4. Enable multi-factor authentication everywhere\n5. Train staff to question urgency, not just grammar`,
    date: "2026-07-05",
    severity: "medium",
    Icon: Mail,
  },
  {
    id: 4,
    category: "threat-alert",
    title: "Fake KRA Tax Refund Portals Surge During Filing Season",
    summary: "Multiple phishing websites mimicking the KRA iTax portal have emerged, targeting taxpayers with fake refund notifications and PIN reset pages.",
    body: `With tax filing deadlines approaching, cybercriminals have launched a coordinated campaign of fake KRA portals targeting Kenyan taxpayers.\n\n## Attack Details\n\n- Over 12 fake iTax domains have been identified (kra-refund.com, itax-verify.xyz, etc.)\n- Victims receive SMS or email claiming a tax refund is available\n- The phishing sites look nearly identical to the real iTax portal\n- Sites harvest KRA PINs, passwords, and personal information\n\n## Known Malicious Domains\n\n- kra-refund.com\n- itax-verify.xyz\n- kra-tax-clearance.com\n- itax-kra-portal.xyz\n\nAll of these are flagged in CyberSense's threat intelligence database.\n\n## How to Stay Safe\n\n1. Always navigate directly to itax.kra.go.ke — never through links\n2. KRA will never ask for your password via email or SMS\n3. Scan suspicious URLs with CyberSense before visiting\n4. Report fake KRA sites to reportincident@kra.go.ke`,
    date: "2026-07-03",
    severity: "high",
    Icon: Landmark,
  },
  {
    id: 5,
    category: "tip",
    title: "Why You Should Enable Two-Factor Authentication Today",
    summary: "Accounts with 2FA enabled are 99.9% less likely to be compromised. Here's a quick guide to enabling it on your most important accounts.",
    body: `Two-factor authentication (2FA) is the single most effective step you can take to protect your online accounts.\n\n## The Numbers\n\n- 99.9% of automated attacks are blocked by 2FA (Microsoft)\n- 80% of data breaches involve weak or stolen passwords (Verizon DBIR)\n- Only 28% of users have 2FA enabled on their email accounts\n\n## Quick Setup Guide\n\n### Gmail\nSettings → Security → 2-Step Verification → Get Started\n\n### M-Pesa\nMySafaricom App → M-Pesa → Settings → Security\n\n### Social Media\n- Facebook: Settings → Security → Two-Factor Authentication\n- Instagram: Settings → Security → Two-Factor Authentication\n- Twitter/X: Settings → Security → Two-Factor Authentication\n\n### Banking\nMost Kenyan banks offer 2FA through their mobile apps. Contact your bank to enable it.\n\n## Best Practices\n\n1. Use an authenticator app (Google Authenticator, Authy) over SMS\n2. Save backup codes in a safe place\n3. Enable 2FA on your email FIRST — it's the master key to all other accounts\n4. Consider a hardware security key for maximum protection`,
    date: "2026-06-30",
    severity: "low",
    Icon: Shield,
  },
  {
    id: 6,
    category: "threat-alert",
    title: "Public Wi-Fi Attacks Spike in Nairobi CBD",
    summary: "Security researchers detected rogue Wi-Fi hotspots in major malls and cafes in Nairobi, intercepting login credentials and banking data.",
    body: `A cybersecurity audit conducted across Nairobi's central business district found multiple malicious Wi-Fi access points set up to intercept user traffic.\n\n## Findings\n\n- 8 rogue "evil twin" hotspots were found in popular locations\n- Hotspot names mimicked legitimate establishments (e.g., "Java_House_WiFi_Free")\n- Attackers used SSL stripping to downgrade HTTPS connections\n- Banking credentials, email logins, and social media tokens were captured\n\n## Affected Locations\n\nThe audit focused on high-traffic areas including malls, coffee shops, and co-working spaces. Specific locations have been notified.\n\n## How to Protect Yourself\n\n1. Always use a VPN on public Wi-Fi\n2. Verify the exact network name with staff\n3. Avoid logging into banking or sensitive accounts\n4. Look for HTTPS on every site you visit\n5. Turn off auto-connect to open networks\n6. Use mobile data for sensitive transactions`,
    date: "2026-06-27",
    severity: "high",
    Icon: Wifi,
  },
  {
    id: 7,
    category: "insight",
    title: "Phishing Attacks Up 178% in East Africa — 2026 Mid-Year Report",
    summary: "The latest cybersecurity report shows a dramatic increase in phishing incidents across Kenya, Uganda, and Tanzania in the first half of 2026.",
    body: `The Communications Authority of Kenya (CA) and East Africa CERT have released their mid-year threat landscape report showing alarming trends.\n\n## Key Statistics\n\n- 178% increase in reported phishing attacks vs H1 2025\n- Mobile-based attacks (SMS/WhatsApp) grew faster than email phishing\n- Financial services sector most targeted (42% of all attacks)\n- Average financial loss per victim: KSh 47,000\n- Only 12% of victims reported the incident to authorities\n\n## Most Targeted Sectors\n\n1. Financial Services & Mobile Money (42%)\n2. Government & Public Services (18%)\n3. E-commerce & Retail (15%)\n4. Telecommunications (12%)\n5. Healthcare (8%)\n6. Education (5%)\n\n## Trends to Watch\n\n- AI-powered phishing is making attacks harder to detect\n- Cross-platform attacks (email → SMS → WhatsApp) are increasing\n- SIM swap fraud remains a persistent threat\n- Ransomware attacks on Kenyan businesses doubled\n\n## Recommendations\n\n1. Organizations should implement email authentication (SPF, DKIM, DMARC)\n2. Individuals should use tools like CyberSense for scanning suspicious content\n3. Report phishing attempts to KE-CIRT: incident@ke-cirt.go.ke\n4. Enable 2FA on all financial accounts`,
    date: "2026-06-24",
    severity: "medium",
    Icon: TrendingUp,
  },
  {
    id: 8,
    category: "advisory",
    title: "Equity Bank Warns Customers of Fake Mobile App",
    summary: "A fraudulent app impersonating Equity Bank's mobile banking platform has been found on third-party app stores, designed to steal login credentials.",
    body: `Equity Bank has issued an urgent advisory warning customers about a counterfeit mobile banking app circulating on unofficial app stores.\n\n## Details\n\n- The fake app closely resembles Equity's official Equity Mobile app\n- It was distributed through third-party APK download sites and WhatsApp links\n- The app captures login credentials and sends them to attackers\n- Some versions also request SMS permissions to intercept OTPs\n\n## How to Identify the Fake App\n\n- Only download from Google Play Store or Apple App Store\n- Check the developer name: it should be "Equity Group Holdings"\n- Look for the verified badge on the app store listing\n- The official app has 5M+ downloads on Google Play\n\n## If You Installed the Fake App\n\n1. Uninstall it immediately\n2. Change your Equity Bank password from a trusted device\n3. Contact Equity Bank: 0763 000 000\n4. Monitor your account for unauthorized transactions\n5. Enable transaction notifications via SMS\n\n## General App Safety\n\n- Never install banking apps from links sent via SMS or WhatsApp\n- Enable Google Play Protect on Android devices\n- Keep your phone's operating system updated\n- Use CyberSense to scan suspicious URLs before downloading anything`,
    date: "2026-06-20",
    severity: "high",
    Icon: ShieldAlert,
  },
];

const severityConfig = {
  critical: { label: "Critical", tone: "bg-red-50 text-red-700 dark:bg-red-500/10 dark:text-red-300", dot: "bg-red-500" },
  high: { label: "High", tone: "bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300", dot: "bg-rose-500" },
  medium: { label: "Medium", tone: "bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300", dot: "bg-amber-500" },
  low: { label: "Info", tone: "bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300", dot: "bg-emerald-500" },
};

const categoryConfig = {
  "threat-alert": { label: "Threat Alert", tone: "bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300" },
  advisory: { label: "Advisory", tone: "bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300" },
  insight: { label: "Insight", tone: "bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-300" },
  tip: { label: "Security Tip", tone: "bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300" },
};

const filterOptions = ["all", "threat-alert", "advisory", "insight", "tip"];

export default function SecurityNews() {
  const [filter, setFilter] = useState("all");
  const [selected, setSelected] = useState(null);

  const filtered = filter === "all" ? NEWS_ITEMS : NEWS_ITEMS.filter((item) => item.category === filter);

  return (
    <section>
      <div className="mb-5">
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-600">Threat intelligence</p>
        <h1 className="mt-2 text-3xl font-extrabold dark:text-white">Security News</h1>
        <p className="mt-2 text-slate-500">Stay informed about the latest cybersecurity threats and advisories.</p>
      </div>

      {/* Filters */}
      <div className="mb-5 flex gap-2 overflow-x-auto">
        {filterOptions.map((item) => (
          <button
            key={item}
            type="button"
            onClick={() => setFilter(item)}
            className={`min-h-10 shrink-0 rounded-xl px-3 text-xs font-bold capitalize ${
              filter === item
                ? "bg-cyan-600 text-white"
                : "bg-white text-slate-500 dark:bg-slate-900"
            }`}
          >
            {item === "all" ? "All" : (categoryConfig[item]?.label || item)}
          </button>
        ))}
      </div>

      {/* News grid */}
      <div className="grid gap-4 md:grid-cols-2">
        {filtered.map((item) => {
          const sev = severityConfig[item.severity] || severityConfig.medium;
          const cat = categoryConfig[item.category] || categoryConfig.advisory;
          const ItemIcon = item.Icon;

          return (
            <article
              key={item.id}
              onClick={() => setSelected(item)}
              className="flex cursor-pointer flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition-colors hover:border-slate-300 hover:bg-slate-50/50 dark:border-slate-800 dark:bg-slate-900 dark:hover:border-slate-700 dark:hover:bg-slate-800/50"
            >
              <div className="flex items-center justify-between gap-2">
                <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${cat.tone}`}>
                  {cat.label}
                </span>
                <div className="flex items-center gap-1.5">
                  <span className={`h-2 w-2 rounded-full ${sev.dot}`} />
                  <span className="text-[11px] font-bold text-slate-400">{sev.label}</span>
                </div>
              </div>

              <div className="mt-4 flex items-start gap-3.5 flex-1">
                <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400">
                  <ItemIcon size={19} strokeWidth={2} />
                </span>
                <div className="min-w-0 flex-1">
                  <h2 className="text-[15px] font-extrabold leading-snug dark:text-white">{item.title}</h2>
                  <p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{item.summary}</p>
                </div>
              </div>

              <div className="mt-5 flex items-center justify-between">
                <p className="text-xs font-semibold text-slate-400">
                  {new Date(item.date).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}
                </p>
                <span className="flex items-center gap-1 text-xs font-bold text-cyan-600 dark:text-cyan-400">
                  Read more <ArrowUpRight size={13} />
                </span>
              </div>
            </article>
          );
        })}
      </div>

      {/* Detail modal */}
      {selected && (
        <ActionModal title={selected.title} onClose={() => setSelected(null)}>
          <article className="p-6 sm:p-8">
            <div className="flex flex-wrap items-center gap-2 text-xs font-bold">
              <span className={`inline-flex rounded-full px-2.5 py-1 ${(categoryConfig[selected.category] || categoryConfig.advisory).tone}`}>
                {(categoryConfig[selected.category] || categoryConfig.advisory).label}
              </span>
              <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 ${(severityConfig[selected.severity] || severityConfig.medium).tone}`}>
                <span className={`h-1.5 w-1.5 rounded-full ${(severityConfig[selected.severity] || severityConfig.medium).dot}`} />
                {(severityConfig[selected.severity] || severityConfig.medium).label}
              </span>
              <span className="text-slate-400">·</span>
              <span className="text-slate-500">
                {new Date(selected.date).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}
              </span>
            </div>
            <p className="mt-5 whitespace-pre-wrap text-[15px] leading-7 text-slate-600 dark:text-slate-300">
              {selected.body}
            </p>
          </article>
        </ActionModal>
      )}
    </section>
  );
}
